name: WheelChairPlugin
main: me.marquez.wcp.WheelChairPlugin
version: ${version}
api-version: 1.16
author: DevMarquez
softdepend:
  - ProtocolLib
commands:
  wcp:
    description: The default command of WheelChairPlugin.